### ISSUE TITLE
some files are missing

### ISSUE THREAD

**Issue by vanchope** [esonghori/TinyGarble#3]
Hi,

I am trying to reproduce the tests via yosys, but it seems like some files are missing.

TinyGarble/circuit_synthesis/sum$ cat sum.yos 
read_verilog sum.v 
hierarchy -check -top sum
proc; opt; fsm; opt; memory; opt;
techmap -map ../lib/stdcells_S.v
opt
dfflibmap -liberty ../lib/asic_cell_yosys_extended.lib
abc -liberty ../lib/asic_cell_yosys_extended.lib -script ../lib/script.abc
opt; clean; opt;
write_verilog syn_yos/sum_syn_yos.v

Where do I find "stdcells_S.v" and "script.abc" ?

Thanks,
Ivan

**Comment by esonghori** [comment]
Hi Ivan, 
Sorry I just saw your comment. I will look at it.

Thanks,
Ebi

**Comment by esonghori** [comment]
Hi Ivan,

I just added the files. Thanks for raising the issue.

Ebi
