### ISSUE TITLE
Is it possible to log time in microseconds instead of clock cycles?

### ISSUE THREAD

**Issue by Bazalia** [esonghori/TinyGarble#6]
Is there an option to do that or a way to convert clock cycles to microseconds. If not how can I go about doing that in the code?

**Comment by esonghori** [comment]
The reported clock cycles is the CPU cycle, so if you know your CPU clock cycle frequency, you can easily calculate the time in second (e.g., in Ubuntu, run `$lscpu | grep "MHz"`). 
Unfortunately, there is no option or arguments to report the timing in seconds, you have to convert it manually using the above method.

**Comment by Bazalia** [comment]
Ok thank you.
